fix: update full-build-in-ci-docker.yaml
fixed input parameters and environment
https://github.com/Netcracker/qubership-workflow-hub/issues/439

diff --git a/.github/workflows/full-build-in-ci-docker.yaml b/.github/workflows/full-build-in-ci-docker.yaml
--- a/.github/workflows/full-build-in-ci-docker.yaml
+++ b/.github/workflows/full-build-in-ci-docker.yaml
@@ -1,8 +1,10 @@
 ---
 
 name: "Build OpenSearch in CI Docker"
-run-name: "OpenSearch ${{ inputs.open-search-tag }} with Custom Patches from ${{ inputs.patches-dir}}"
+run-name: "OpenSearch ${{ inputs.open-search-tag || '3.4.0' }} with Custom Patches from ${{ inputs.patches-dir || 'patches/3.4.0' }}"
 on:
+  schedule:
+    - cron: 0 0 1 * *
   workflow_dispatch:
     inputs:
       open-search-tag:
@@ -15,7 +17,7 @@ on:
         description: "Direcory in this repository with patches"
         required: true
         default: "patches/3.4.0"
-      tags:
+      target-branch:
         type: string
         required: true
         default: "main"
@@ -35,11 +37,17 @@ on:
         description: "Trigger qubership-opensearch build"
         default: true
         required: false
+
 permissions:
   contents: read
 env:
-  custom_branch: "applied-patches-${{ github.event.inputs.open-search-tag }}-${{ github.run_id }}"
-  default_custom_tag: "ghcr.io/${{ github.repository_owner }}/opensearch:${{ github.event.inputs.open-search-tag }}-custom-patches"
+  OPEN_SEARCH_TAG: "${{ inputs.open-search-tag || '3.4.0' }}"
+  PATCHES_DIR: "${{ inputs.patches-dir || 'patches/3.4.0' }}"
+  TARGET_BRANCH: "${{ inputs.target-branch || 'main' }}"
+  INTEGRATION_TEST: "${{ inputs.integration-tests || 'true' }}"
+  DOCKER_TEST: "${{ inputs.docker-test || 'true' }}"
+  custom_branch: "applied-patches-${{ github.event.inputs.open-search-tag || '3.4.0' }}-${{ github.run_id }}"
+  default_custom_tag: "ghcr.io/${{ github.repository_owner }}/opensearch:${{ github.event.inputs.open-search-tag || '3.4.0' }}-custom-patches"
 
 jobs:
   apply-patches:
@@ -52,7 +60,7 @@ jobs:
         uses: actions/checkout@v5
         with:
           repository: opensearch-project/opensearch
-          ref: ${{ inputs.open-search-tag }}
+          ref: ${{ env.OPEN_SEARCH_TAG }}
           path: opensearch
       - name: "Checkout this repository"
         uses: actions/checkout@v5
@@ -62,7 +70,7 @@ jobs:
       - name: "Apply patches"
         run: |
           cd ${GITHUB_WORKSPACE}/opensearch
-          for p in ../opensearch-custom-patches/${{ inputs.patches-dir }}/*.patch; do
+          for p in ../opensearch-custom-patches/${{ env.PATCHES_DIR }}/*.patch; do
             echo "Applying $p…"
             git apply -p1 --ignore-space-change --ignore-whitespace "$p"
           done
@@ -75,7 +83,7 @@ jobs:
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
           git checkout -b "${{ env.custom_branch }}"
           git add .
-          git commit -m "Applied custom patches to OpenSearch ${{ inputs.open-search-tag }}"
+          git commit -m "Applied custom patches to OpenSearch ${{ env.OPEN_SEARCH_TAG }}"
           git push origin "${{ env.custom_branch }}"
 
   build-in-docker:
@@ -134,8 +142,8 @@ jobs:
           git clone https://github.com/opensearch-project/opensearch-build.git
           cd opensearch-build
           # Modify build configuration to use patched OpenSearch
-          if [ ! -f manifests/${{ inputs.open-search-tag }}/opensearch-${{ inputs.open-search-tag }}.yml ]; then
-            echo "Error: Build manifest for OpenSearch tag ${{ inputs.open-search-tag }} does not exist."
+          if [ ! -f manifests/${{ env.OPEN_SEARCH_TAG }}/opensearch-${{ env.OPEN_SEARCH_TAG }}.yml ]; then
+            echo "Error: Build manifest for OpenSearch tag ${{ env.OPEN_SEARCH_TAG }} does not exist."
             exit 1
           fi
           sed -i '
@@ -143,8 +151,8 @@ jobs:
           s|^\([[:space:]]*\)repository:.*|\1repository: https://github.com/${{ github.repository }}.git|
           s|^\([[:space:]]*\)ref:.*|\1ref: ${{ env.custom_branch }}|
           }
-          ' manifests/${{ inputs.open-search-tag }}/opensearch-${{ inputs.open-search-tag }}.yml
-          ./build.sh manifests/${{ inputs.open-search-tag }}/opensearch-${{ inputs.open-search-tag }}.yml --platform linux -a ${{ matrix.platform.architecture }}
+          ' manifests/${{ env.OPEN_SEARCH_TAG }}/opensearch-${{ env.OPEN_SEARCH_TAG }}.yml
+          ./build.sh manifests/${{ env.OPEN_SEARCH_TAG }}/opensearch-${{ env.OPEN_SEARCH_TAG }}.yml --platform linux -a ${{ matrix.platform.architecture }}
           ./assemble.sh tar/builds/opensearch/manifest.yml
           """ > ${GITHUB_WORKSPACE}/scripts/run-build.sh
           cat ${GITHUB_WORKSPACE}/scripts/run-build.sh
@@ -163,10 +171,10 @@ jobs:
           path: |
             ${{ github.workspace }}/build-artifacts/${{ matrix.platform.architecture }}/*.tar.gz
       - name: Execute integration tests (optional)
-        if: ${{ inputs.integration-tests }}
+        if: ${{ env.INTEGRATION_TEST }}
         run: |
           echo "Triggering opensearch integration tests..."
-          docker exec --user ci-runner ci-docker bash -c "cd /home/ci-runner/opensearch-build && mv -rf tar/* . && ./test.sh integ-test manifests/${{ inputs.open-search-tag }}/opensearch-${{ inputs.open-search-tag }}-test.yml"
+          docker exec --user ci-runner ci-docker bash -c "cd /home/ci-runner/opensearch-build && mv -rf tar/* . && ./test.sh integ-test manifests/${{ env.OPEN_SEARCH_TAG }}/opensearch-${{ env.OPEN_SEARCH_TAG }}-test.yml"
   build-and-push-docker:
     permissions:
       contents: read
@@ -174,21 +182,20 @@ jobs:
     uses: netcracker/opensearch-patches/.github/workflows/re-docker-build.yaml@main
     needs: build-in-docker
     with:
-      open-search-tag: ${{ inputs.open-search-tag }}
-      docker-test: ${{ inputs.docker-test }}
+      opensearch-tag: "${{ inputs.open-search-tag || '3.4.0' }}"
+      docker-test: ${{ inputs.docker-test || 'true' }}
 
   trigger-qubership-opensearch-build:
-    if: ${{ inputs.trigger-qubership-opensearch-build == true }}
+    if: ${{ inputs.trigger-qubership-opensearch-build == true || true }}
     name: "Trigger qubership-opensearch build"
     needs: [build-and-push-docker]
     runs-on: ubuntu-latest
     steps:
       - name: "Trigger ${{ github.event.repository.name }}/qubership-opensearch build"
-        if: ${{ inputs.trigger-qubership-opensearch-build }}
         uses: netcracker/qubership-workflow-hub/actions/custom-event@v2.0.1
         with:
           github-token: ${{ secrets.GH_ACCESS_TOKEN }}
           owner: ${{ github.repository_owner }}
           repo: qubership-opensearch
           event-type: opensearch-patched-build
-          client-payload: '{"opensearch_tag": "${{ inputs.opensearch-tag }}", "custom_opensearch_version": "${{ env.default_custom_tag }}", "target_branch": "${{ inputs.target-branch }}"}'
+          client-payload: '{"opensearch_tag": "${{ env.OPEN_SEARCH_TAG }}", "custom_opensearch_version": "${{ env.default_custom_tag }}", "target_branch": "${{ env.TARGET_BRANCH }}"}'
